AppBundle\Entity\Users:
    properties:
        name:
          - NotBlank: ~
        login:
          - NotBlank: ~
        password:
          - NotBlank: ~
        moderator:
          - NotBlank: ~