# src/AppBundle/Resources/config/doctrine/Emails.orm.yml
AppBundle\Entity\Emails:
    type: entity
    table: Emails
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        uid:
            type: integer
            length: 11
        address:
            type: string
            length: 100
        test:
            type: string
            length: 100
    manyToOne:
            users:
                targetEntity: AppBundle\Entity\Users
                inversedBy: emails
                joinColumn:
                    name: uid
                    referencedColumnName: id